version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: hb_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hb
      POSTGRES_PASSWORD: hb_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hb_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: hb_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pg_data: